insert into word (id,string,'language',level,used) values (1, 'One','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (2, 'Two','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (3, 'Three','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (4, 'Four','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (5, 'Five','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (6, 'Six','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (7, 'Seven','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (8, 'Eight','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (9, 'Nine','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (10, 'Ten','ENGLISH','EASY',0);
insert into word (id,string,'language',level,used) values (11, 'OneOne','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (12, 'TwoTwo','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (13, 'ThreeThree','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (14, 'FourFour','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (15, 'FiveFive','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (16, 'SixSix','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (17, 'SevenSeven','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (18, 'EightEight','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (19, 'NineNine','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (20, 'TenTen','ENGLISH','MIDDLE',0);
insert into word (id,string,'language',level,used) values (21, 'OneOneOne','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (22, 'TwoTwoTwo','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (23, 'ThreeThreeThree','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (24, 'FourFourFour','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (25, 'FiveFiveFive','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (26, 'SixSixSix','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (27, 'SevenSevenSeven','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (28, 'EightEightEight','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (29, 'NineNineNine','ENGLISH','HARD',0);
insert into word (id,string,'language',level,used) values (30, 'TenTenTen','ENGLISH','HARD',0);

insert into player (id,login,email,name,password) values (1, 'yuta4', 'yura.berezin@gmail.com','Yura','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,login,email,name,password) values (2, 'irunia', 'gapchukirina@gmail.com','Irunia','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,login,email,name,password) values (3, 'dima_rk_15', 'dimka@gmail.com','Dima','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,login,email,name,password) values (4, 'anna', 'anna@gmail.com','Anna','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,login,email,name,password) values (5, 'lesya', 'lesya@gmail.com','Lesya','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,login,email,name,password) values (6, 'Mafiozy', 'yuraf@gmail.com','Yura','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');

SELECT * FROM GAME ;
SELECT * FROM GAME_WORD  ;
SELECT * FROM PLAYER  ;
SELECT * FROM TEAM  ;
SELECT * FROM TEAM_PLAYERS  ;
SELECT * FROM WORD  ;
SELECT * FROM GAME_WATCHER