insert into word (id,string,level,used) values (1, 'One','EASY',0);
insert into word (id,string,level,used) values (2, 'Two','EASY',0);
insert into word (id,string,level,used) values (3, 'Three','EASY',0);
insert into word (id,string,level,used) values (4, 'Four','EASY',0);
insert into word (id,string,level,used) values (5, 'Five','EASY',0);
insert into word (id,string,level,used) values (6, 'Six','EASY',0);
insert into word (id,string,level,used) values (7, 'Seven','EASY',0);
insert into word (id,string,level,used) values (8, 'Eight','EASY',0);
insert into word (id,string,level,used) values (9, 'Nine','EASY',0);
insert into word (id,string,level,used) values (10, 'Ten','EASY',0);
insert into word (id,string,level,used) values (11, 'OneOne','MIDDLE',0);
insert into word (id,string,level,used) values (12, 'TwoTwo','MIDDLE',0);
insert into word (id,string,level,used) values (13, 'ThreeThree','MIDDLE',0);
insert into word (id,string,level,used) values (14, 'FourFour','MIDDLE',0);
insert into word (id,string,level,used) values (15, 'FiveFive','MIDDLE',0);
insert into word (id,string,level,used) values (16, 'SixSix','MIDDLE',0);
insert into word (id,string,level,used) values (17, 'SevenSeven','MIDDLE',0);
insert into word (id,string,level,used) values (18, 'EightEight','MIDDLE',0);
insert into word (id,string,level,used) values (19, 'NineNine','MIDDLE',0);
insert into word (id,string,level,used) values (20, 'TenTen','MIDDLE',0);
insert into word (id,string,level,used) values (21, 'OneOneOne','HARD',0);
insert into word (id,string,level,used) values (22, 'TwoTwoTwo','HARD',0);
insert into word (id,string,level,used) values (23, 'ThreeThreeThree','HARD',0);
insert into word (id,string,level,used) values (24, 'FourFourFour','HARD',0);
insert into word (id,string,level,used) values (25, 'FiveFiveFive','HARD',0);
insert into word (id,string,level,used) values (26, 'SixSixSix','HARD',0);
insert into word (id,string,level,used) values (27, 'SevenSevenSeven','HARD',0);
insert into word (id,string,level,used) values (28, 'EightEightEight','HARD',0);
insert into word (id,string,level,used) values (29, 'NineNineNine','HARD',0);
insert into word (id,string,level,used) values (30, 'TenTenTen','HARD',0);

insert into player (id,email,name,password) values (1, 'yura.berezin@gmail.com','Yura','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,email,name,password) values (2, 'gapchukirina@gmail.com','Irunia','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,email,name,password) values (3, 'dimka@gmail.com','Dima','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,email,name,password) values (4, 'anna@gmail.com','Anna','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,email,name,password) values (5, 'lesya@gmail.com','Lesya','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');
insert into player (id,email,name,password) values (6, 'yuraf@gmail.com','Yura','$2a$10$wp1nBzyZwh6cX3jn31NfW.H4IT3mspVB6USZhVpSqC4dLH0QFHlmi');

SELECT * FROM GAME ;
SELECT * FROM GAME_WORD  ;
SELECT * FROM PLAYER  ;
SELECT * FROM TEAM  ;
SELECT * FROM TEAM_PLAYERS  ;
SELECT * FROM WORD  ;