spring:
  datasource:
    url: jdbc:h2:file:/home/iurii/Personal/data/hat
    driverClassName: org.h2.Driver
    username: sa
    password: password
#    hikari:
#      poolName: hikari_pool
#      leakDetectionThreshold: 2000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
  console:
    enabled: true
  flyway:
    enabled: false
#logging:
#  level:
#    com.zaxxer.hikari: DEBUG
